puddle/item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns =[
    path('<int:pk>/', views.detail, name='detail'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index,contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('',index,name='index'),
    path('contact/',contact,name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model): 
    name = models.CharField(max_length=255) #defining name here

    class Meta:
        ordering =('name',)
        verbose_name_plural = 'Categories' #changing categorys to category

    def __str__(self):
        return self.name #categories item 1,2 was showing for fixing this so that the function would return its own defined name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.TextField(blank=True, null=True) #defining name here
    price = models.FloatField()
    description = models.TextField(blank=True, null=True)
    is_sold = models.BooleanField(default=False) #defining
    created_at = models.DateTimeField(auto_now_add=True) #defining created_at
    created_by = models.ForeignKey(User,related_name='items' ,on_delete=models.CASCADE) #defining created_by and On_delete=CASCADE means when a user is deleted all items are deleted which had been created by user before
    image = models.ImageField(upload_to='item_images',blank=True, null=True) #defining image
    
    def __str__(self):
        return self.name

puddle/core/views.py
from django.shortcuts import render
from item.models import Item, Category
# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html', {
    })

puddle/item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)

    return render(request, 'item/detail.html', {
        'item': item,
    })

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Puddle</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href"#" class="text-xl font semibold">Puddle</a>
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">New items</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            <a href="#" class="py-3 px-3 text-lg font-semibold bg-teal-500 text-white rounded xl hover:bg-teal-700">Sign up</a>
            <a href="#" class="py-3 px-3 text-lg font-semibold bg-blue-500 text-white rounded xl hover:bg-blue-700">Log in</a>
        </div>
    </nav>
<div class="px-6 py-6">
   {% block content %}
   
   {% endblock %}
</div>
<footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-grey-500">Lorem Lorem Lorem Lorem Lorem </p>
    </div>
    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
            <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html'%}
{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
    {% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html'%}
{% block title %}Welcome{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">All items</h2>
  <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
      <div>
        <a href="{% url 'item:detail' item.id %}">
          <div>
              <img src="{{ item.image.url }}" class="rounded-t-xl">
          </div>

          <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ item.name }} </h2>
              <p class="text-gray-400"> Price : {{ item.price }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
  </div>

</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Categories</h2>
  <div class="grid grid-cols-3 gap-3">
      {% for category in categories %}
      <div>
        <a href="#">
        
          <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ category.name }} </h2>
              <p class="text-gray-400">{{ category.items.count }} Items</p>
          </div>
        </a>
      </div>
      {% endfor %}
  </div>

</div>
{% endblock %}

puddle/item/templates/item/detail.html
{% extends 'core/base.html'%}

{% block title %}{{ item.name }}{% endblock %}
{% block content %}

 <div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

 </div>
{% endblock %}